credentials:
  usernames:
    youssef:
      email: ychafiqui2@gmail.com
      name: Youssef Chafiqui
      password: '$2b$12$tOddznIiq93o0vH0dwzZfOrpCUz0xNzgpTryEazTtCjwnBbAvv61O'
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - test@gmail.com
