credentials:
  usernames:
    youssef:
      email: ychafiqui2@gmail.com
      name: Youssef Chafiqui
      password: '$2b$12$8gMFcqMbANmz13zJ.OJzp.LBuQVzFtR8b3Kr.p5kruSIB55TMBICO'
cookie:
  expiry_days: 30
  key: random_signature_key
  name: random_cookie_name
preauthorized:
  emails:
  - test@gmail.com
